-- Seed cabang dari list-nama-cabang.md (overwrite nama utk kode cocok,
-- insert yang belum ada, cabang di luar file dibiarkan).
-- Kode dicocokkan ternormalisasi (AW01 → AW1: buang nol leading setelah AW)
-- agar tidak terjadi cabang dobel.
UPDATE cabang AS c
SET kode = s.kode, nama = s.nama
FROM (VALUES
  ('AW1',  'AL-WILDAN ISLAMIC SCHOOL 1 GADING SERPONG'),
  ('AW3',  'AL-WILDAN ISLAMIC SCHOOL 3 BSD CITY'),
  ('AW4',  'AL-WILDAN ISLAMIC SCHOOL 4 JAKARTA SELATAN'),
  ('AW5',  'AL-WILDAN ISLAMIC SCHOOL 5 JAKARTA PUSAT'),
  ('AW7',  'AL-WILDAN ISLAMIC SCHOOL 7 SERANG'),
  ('AW8',  'AL-WILDAN ISLAMIC SCHOOL 8 KEMANG, BOGOR'),
  ('AW10', 'AL-WILDAN ISLAMIC SCHOOL 10 JAKARTA TIMUR'),
  ('AW11', 'AL-WILDAN ISLAMIC SCHOOL 11 JAKARTA PUSAT'),
  ('AW12', 'AL-WILDAN ISLAMIC SCHOOL 12 BEKASI'),
  ('AW13', 'AL-WILDAN ISLAMIC SCHOOL 13 BEKASI'),
  ('AW14', 'AL-WILDAN ISLAMIC SCHOOL 14 BUMI MUTIARA'),
  ('AW15', 'AL-WILDAN ISLAMIC SCHOOL 15 BEKASI'),
  ('AW16', 'AL-WILDAN ISLAMIC SCHOOL 16 CILEDUG'),
  ('AW19', 'AL-WILDAN ISLAMIC SCHOOL 19 JAKARTA BARAT'),
  ('AW20', 'AL-WILDAN ISLAMIC SCHOOL 20 MATARAM'),
  ('AW21', 'AL-WILDAN ISLAMIC SCHOOL 21 ACEH'),
  ('AW22', 'AL-WILDAN ISLAMIC SCHOOL 22 MAKASSAR'),
  ('AW23', 'AL-WILDAN ISLAMIC SCHOOL 23 SEMARANG'),
  ('AW24', 'AL-WILDAN ISLAMIC SCHOOL 24 YOGYAKARTA'),
  ('AW28', 'AL-WILDAN ISLAMIC SCHOOL 28 GRAND WISATA, BEKASI'),
  ('AW29', 'AL-WILDAN ISLAMIC SCHOOL 29 DEPOK'),
  ('AW30', 'AL-WILDAN ISLAMIC SCHOOL 30 BEKASI'),
  ('AW31', 'AL-WILDAN ISLAMIC SCHOOL 31 CIBINONG'),
  ('AW32', 'AL-WILDAN ISLAMIC SCHOOL 32 JAKARTA TIMUR')
) AS s(kode, nama)
WHERE regexp_replace(lower(c.kode), '^aw0+', 'aw') =
      regexp_replace(lower(s.kode), '^aw0+', 'aw');
--> statement-breakpoint
INSERT INTO cabang (kode, nama)
SELECT s.kode, s.nama
FROM (VALUES
  ('AW1',  'AL-WILDAN ISLAMIC SCHOOL 1 GADING SERPONG'),
  ('AW3',  'AL-WILDAN ISLAMIC SCHOOL 3 BSD CITY'),
  ('AW4',  'AL-WILDAN ISLAMIC SCHOOL 4 JAKARTA SELATAN'),
  ('AW5',  'AL-WILDAN ISLAMIC SCHOOL 5 JAKARTA PUSAT'),
  ('AW7',  'AL-WILDAN ISLAMIC SCHOOL 7 SERANG'),
  ('AW8',  'AL-WILDAN ISLAMIC SCHOOL 8 KEMANG, BOGOR'),
  ('AW10', 'AL-WILDAN ISLAMIC SCHOOL 10 JAKARTA TIMUR'),
  ('AW11', 'AL-WILDAN ISLAMIC SCHOOL 11 JAKARTA PUSAT'),
  ('AW12', 'AL-WILDAN ISLAMIC SCHOOL 12 BEKASI'),
  ('AW13', 'AL-WILDAN ISLAMIC SCHOOL 13 BEKASI'),
  ('AW14', 'AL-WILDAN ISLAMIC SCHOOL 14 BUMI MUTIARA'),
  ('AW15', 'AL-WILDAN ISLAMIC SCHOOL 15 BEKASI'),
  ('AW16', 'AL-WILDAN ISLAMIC SCHOOL 16 CILEDUG'),
  ('AW19', 'AL-WILDAN ISLAMIC SCHOOL 19 JAKARTA BARAT'),
  ('AW20', 'AL-WILDAN ISLAMIC SCHOOL 20 MATARAM'),
  ('AW21', 'AL-WILDAN ISLAMIC SCHOOL 21 ACEH'),
  ('AW22', 'AL-WILDAN ISLAMIC SCHOOL 22 MAKASSAR'),
  ('AW23', 'AL-WILDAN ISLAMIC SCHOOL 23 SEMARANG'),
  ('AW24', 'AL-WILDAN ISLAMIC SCHOOL 24 YOGYAKARTA'),
  ('AW28', 'AL-WILDAN ISLAMIC SCHOOL 28 GRAND WISATA, BEKASI'),
  ('AW29', 'AL-WILDAN ISLAMIC SCHOOL 29 DEPOK'),
  ('AW30', 'AL-WILDAN ISLAMIC SCHOOL 30 BEKASI'),
  ('AW31', 'AL-WILDAN ISLAMIC SCHOOL 31 CIBINONG'),
  ('AW32', 'AL-WILDAN ISLAMIC SCHOOL 32 JAKARTA TIMUR')
) AS s(kode, nama)
WHERE NOT EXISTS (
  SELECT 1 FROM cabang c
  WHERE regexp_replace(lower(c.kode), '^aw0+', 'aw') =
        regexp_replace(lower(s.kode), '^aw0+', 'aw')
);
